InfluxSrv:
  image: "tutum/influxdb:0.8.8"
  volumes:
    - "/data2/influxdb:/data:rw"
  ports:
    - "8083:8083"
    - "8086:8086"
  expose:
    - "8090"
    - "8099"
  environment:
    - PRE_CREATE_DB=cadvisor
cadvisor:
  image: "google/cadvisor"
  volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
  links:
    - "InfluxSrv:influxsrv"
  ports:
    - "8080:8080"
  command: "-storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086"
grafana:
  image: "commarla/grafana:latest"
  volumes:
    - "/data2/grafana/var:/var/lib/grafana:rw"
    - "/data2/grafana/etc:/etc/grafana:rw"
  ports:
    - "3000:3000"
  environment:
    - INFLUXDB_HOST=influxsrv
    - INFLUXDB_PORT=8086
    - INFLUXDB_NAME=cadvisor
    - INFLUXDB_USER=root
    - INFLUXDB_PASS=root
  links:
    - "InfluxSrv:influxsrv"
